### ISSUE TITLE
JavaScript in-memory minification speed

### ISSUE THREAD

**Issue by tshemsedinov** [tshemsedinov/impress#367]
In a few last versions minification has slowed down. It may be problem of uglify-js, I will check it.

**Comment by tshemsedinov** [comment]
Тут нужно Проверить скорость работы ```uglify-js```, раньше статика отдавалась быстро и первый раз и последующие, теперь первый GET к статике медленный, а потом она кешируется в памяти и все последующие быстрые. Кеширование було и раньше, от него первый GET не зависит, и мне кажется, что ```uglify-js``` стал существенно тормозить. Нужно определить, с какой версии ```uglify-js``` стал себя так вести, если это его вина. И что можно с этим сделать, может нам откатиться на его предыдщие версии, земенить ругой реализацией или ему можно дать какие-то настройки, чтобы он не тормозил или мы можем исправить сам ```uglify-js```. @johnbizokk и @ReasonX7 может возьмете это задание?

**Comment by j-martyn** [comment]
Проблема у них там известная, что-то там связано с `v8`, вроде там даже про `vm` что-то мелькало, и что с каждой новой версией ноды оно всё медленнее
[mishoo/UglifyJS2#636](/mishoo/UglifyJS2/issues/636)

А в нашем случае картина такая
```
impress minify: 4663ms
filePath = c:/Users/j_mart/PhpstormProjects/impress/applications/example/static/js/jquery.min.js
impress minify: 180ms
filePath = c:/Users/j_mart/PhpstormProjects/impress/applications/example/static/js/eventsource.min.js
impress minify: 130ms
filePath = c:/Users/j_mart/PhpstormProjects/impress/applications/example/static/js/impress.rpc.js
impress minify: 363ms
filePath = c:/Users/j_mart/PhpstormProjects/impress/applications/example/static/js/impress.js
impress minify: 227ms
filePath = c:/Users/j_mart/PhpstormProjects/impress/applications/example/static/js/wcl.js
impress minify: 98ms
filePath = c:/Users/j_mart/PhpstormProjects/impress/applications/example/static/js/init.js
pre: 98ms
```
Подробнее для `jQuery` (который и так уже минифицирован, и после `uglify` даже становиться чуток больше :) )
```
parse: 916ms

compress  
  merge: 0ms
  figure_out_scope: 217ms
  Compressor: 1ms
  transform: 2604ms
compress: 2823ms

mangle  
  figure_out_scope: 193ms
  compute_char_frequency: 462ms
  mangle_names: 61ms
mangle: 716ms

output: 204ms

impress minify: 4663ms
filePath = c:/Users/j_mart/PhpstormProjects/impress/applications/example/static/js/jquery.min.js
```

После терапии путём добавления параметров  для отключения `compress` и `mangle` в `lib/impress.preprocess.js:25`
```
api.uglify.minify(files, {
      fromString: true,
      compress: false,
      mangle:false,
    })
```
картина такая
```
parse: 487ms
compress: 0ms
mangle: 0ms
output: 218ms
impress minify: 706ms
filePath = c:/Users/j_mart/PhpstormProjects/impress/applications/example/static/js/jquery.min.js
```
это все на ноде 0.12.7. а на  0.10.31, оно конечно получше, но тоже медленно
c `compress` и `mangle` 
```
parse: 548ms

compress:
  merge: 1ms
  figure_out_scope: 157ms
  Compressor: 0ms
  transform: 1284ms
  compress: 1442ms

mangle: 
  figure_out_scope: 119ms
  compute_char_frequency: 325ms
  mangle_names: 48ms
mangle: 494ms

output: 151ms

impress minify: 2637ms
filePath = c:/Users/j_mart/PhpstormProjects/impress/applications/example/static/js/jquery.min.js
```
без `compress` и `mangle` 
```
parse: 499ms
compress: 0ms
mangle: 1ms
output: 276ms
impress minify: 778ms
filePath = c:/Users/j_mart/PhpstormProjects/impress/applications/example/static/js/jquery.min.js
```
Что эти параметры делают:
https://github.com/mishoo/UglifyJS2#compressor-options
https://github.com/mishoo/UglifyJS2#mangler-options
